name: maldives_reef_life
description: Maldivian Fish
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.4+10

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  accordion: ^2.5.1
  gradient_widgets: ^0.6.0
  persistent_bottom_nav_bar: ^6.2.1 #TODO: delete
  flutter_carousel_slider: ^1.1.0
  photo_view: ^0.14.0
  page_transition: ^2.0.9
  url_launcher: ^6.3.1
  url_launcher_ios: ^6.3.2
  http: ^0.13.6
  flutter_bloc: ^8.1.3
  cached_network_image: ^3.3.1
  sqflite: ^2.2.8+4
  flutter_staggered_animations: ^1.0.0
  video_player: ^2.7.2
  flutter_html: any
  path_provider: ^2.1.1
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  full_screen_image: ^2.0.0
  carousel_slider: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  image_path: "assets/img/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  android_12:
    image_path: "assets/img/icon.png"

flutter:

  uses-material-design: true

  assets:
     - assets/img/
     - assets/fishes.db
     - assets/welcome.mp4

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
